/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3f8",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#2f486a",
        "on-tertiary-fixed-variant": "#6b3a25",
        "on-primary-fixed": "#001c3a",
        "secondary-fixed-dim": "#bec7d9",
        "on-surface": "#1a1c1f",
        "inverse-primary": "#afc8f0",
        "tertiary-fixed": "#ffdbce",
        "on-tertiary-fixed": "#351002",
        "surface-container-high": "#e8e8ed",
        "on-secondary-fixed": "#131c29",
        secondary: "#565f6e",
        "outline-variant": "#c4c6cf",
        primary: "#000613",
        "on-primary-container": "#6f88ad",
        "on-error-container": "#93000a",
        "surface-tint": "#476083",
        "tertiary-fixed-dim": "#fdb69a",
        "surface-dim": "#d9dade",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "secondary-container": "#d7e0f2",
        "on-secondary-fixed-variant": "#3e4756",
        "surface-container": "#ededf2",
        surface: "#f9f9fe",
        tertiary: "#110200",
        "surface-container-highest": "#e2e2e7",
        "on-secondary": "#ffffff",
        "tertiary-container": "#391303",
        "surface-variant": "#e2e2e7",
        "inverse-surface": "#2e3034",
        "on-background": "#1a1c1f",
        "on-tertiary-container": "#b5785f",
        "primary-fixed": "#d4e3ff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f0f5",
        "secondary-fixed": "#dae3f5",
        "primary-fixed-dim": "#afc8f0",
        "surface-bright": "#f9f9fe",
        background: "#f9f9fe",
        "primary-container": "#001f3f",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#43474e",
        "on-secondary-container": "#5a6372",
        outline: "#74777f",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
      },
    },
  },
  plugins: [],
};
